# Generated by Django 4.1.7 on 2023-03-28 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('1', 'Bishkek'), ('2', 'Osh'), ('3', 'Batken'), ('4', 'Djalal-Abad'), ('5', 'Naryn'), ('6', 'Talas'), ('7', 'Issyk-Kul'), ('8', 'Chuy')], max_length=1)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile photo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
